### ISSUE TITLE
Undefined variables

### ISSUE THREAD

**Issue by Linneamax** [PlesaLab/DropSynth_code_2023#1]
There are undefined variables on line 59, 84, 88, 90, 94, 108, 303 and 305 in final_oligo_check.py, all of these variables are restriction enzymes. Do you have any suggestions on how to solve this?

**Comment by voyn** [comment]
These are all restriction enzymes defined in the [Restriction package](https://biopython.org/DIST/docs/cookbook/Restriction.html) of BioPython. If BioPython is setup correctly they should be imported.
